//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class continente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public continente()
        {
            this.pais_continente = new HashSet<pais_continente>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public double populacao { get; set; }
        public double area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pais_continente> pais_continente { get; set; }
    }
}
