//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotel()
        {
            this.quarto_hotel = new HashSet<quarto_hotel>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string tipo { get; set; }
        public int id_cidade { get; set; }
    
        public virtual cidade cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quarto_hotel> quarto_hotel { get; set; }
    }
}
