//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pais_continente
    {
        public int id_pais { get; set; }
        public int id_continente { get; set; }
        public int id { get; set; }
    
        public virtual continente continente { get; set; }
        public virtual pais pais { get; set; }
    }
}
