//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class quarto_hotel
    {
        public int id_hotel { get; set; }
        public string tipo { get; set; }
        public double preco { get; set; }
        public int id { get; set; }
    
        public virtual hotel hotel { get; set; }
    }
}
